### ISSUE TITLE
Using esbuild in the renderer

### ISSUE THREAD

**Issue by Zertz** [Kiyozz/electron-esbuild#2]
I'm sure there's a good reason but I was wondering why webpack was chosen for the renderer's build rather than esbuild?

**Comment by Kiyozz** [comment]
Fast refresh is only available via Babel and Webpack (from my research), using esbuild, you will not be able to use scss, module css, and more because esbuild don't support it yet.

In my personal project, I use tailwindcss and need postcss. That's why I use webpack here.

I could include an example using esbuild both sides, but I'm not sure fast refresh will be available.

**Comment by Zertz** [comment]
Fair tradeoffs, thanks for taking the time to answer! I use a *very* similar stack 👀 

It looks like there a few [community plugins](https://github.com/esbuild/community-plugins) for PostCSS so that should be doable!

Fast refresh however is unlikely to happen, at least in the short term as it's heavily dependent on Babel. Persistent state is very cool but I'm thinking in terms of speed, it may not actually matter since esbuild is so much faster?

**Comment by Kiyozz** [comment]
Esbuild is indeed much faster. electron-esbuild could use webpack or esbuild in the renderer.

If we can use postcss in esbuild, I think we are tide again at postcss speed.

I didn't know this community plugins repo, thanks!

**Comment by Kiyozz** [comment]
I'll make a test using a fresh full esbuild main/renderer using less features (basic hello world) and one with Tailwindcss (complicated example)!

**Comment by Zertz** [comment]
That's cool! Let me know how I can help,I don't mean to pressure you into doing this for me!

**Comment by Kiyozz** [comment]
Ok, so, I made a version 1.1.1 which supports esbuild in the renderer. Configuration format changed (see README.md).

If you see any problem, please report here.

Made three examples

1. esbuild both
2. esbuild both using postcss/tailwindcss
3. esbuild in main, webpack in renderer

I'm not doing this for you, but for me too! I use electron-esbuild in another project of mine -> [PCA](https://github.com/Kiyozz/papyrus-compiler-app)

**Comment by Zertz** [comment]
Awesome, I'll give it a try! I'm working on a [MongoDB GUI](https://github.com/Zertz/ElectroMongo)

**Comment by Zertz** [comment]
Works great! The only issue I stumbled upon is that webpack must be installed otherwise [builder.ts](https://github.com/Kiyozz/electron-esbuild/blob/main/src/builder.ts#L13) crashes while trying to import it.

Perhaps the webpack module could be loaded with something along those lines:

```js
try {
  require("webpack")
} catch {
  console.error("It looks like you're trying to use webpack but it's not installed, try running `npm install webpack --dev`");
}
```

Edit: Are you also seeing slow build times? It seems like css is getting rebuilt even when only js changes and both are taking quite a while:

![image](https://user-images.githubusercontent.com/2636763/110160603-3a463200-7dba-11eb-8bed-9fc0a34be698.png)

**Comment by Kiyozz** [comment]
Yes indeed, it will be fixed!

Delay of compilation via esbuild may be the size of your css. What do you have? In the tailwindcss example, I added in the html that, it take 2s because of postcss and size of tailwindcss.

I use esbuild.serve option for the renderer, this function rebuild your asset on demand. If application ask for index.js, it will build both js and css if css is in an import statement (esbuild do not register compiled assets in memory, nothing on disk, only on demand).

**Comment by Zertz** [comment]
Oh interesting, I'll read up on esbuild and see how I can improve things on my end. I literally have three lines of CSS but I do use Tailwind which is huge in development. They're working on a new [PostCSS plugin](https://twitter.com/adamwathan/status/1366509825186795524) that should **significantly** improve build performance!

**Comment by Kiyozz** [comment]
Oh this looks awesome!

**Comment by Kiyozz** [comment]
I made a 1.1.2 which contains fix for webpack and configuration validation.

**Comment by Zertz** [comment]
Thanks for your help, I'll make the switch as soon as Tailwind releases their new plugin!
